name: CI/CD Pipeline

on:
  push:
    branches:
      - ci

  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to netlify
        run: netlify deploy --site "${{secrets.NETLIFY_SECRET}}" --auth "${{secrets.NETLIFY_APP_ID}}" --dir "dist" --prod

